apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-service-envs
data:
  OFFER_SERVICE_PROTOCOL: "http"
  OFFER_SERVICE_HOST: "offerservice"
  OFFER_SERVICE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
        image: gcr.io/dynatrace-demoability/easytrade/aggregatorservice:151f288
        env:
          - name: STARTER_PACKAGE_PROBABILITY
            value: "1"
          - name: LIGHT_PACKAGE_PROBABILITY
            value: "2"
          - name: PRO_PACKAGE_PROBABILITY
            value: "3"
          - name: PLATFORM
            value: "dev"
        envFrom:
          - configMapRef:
              name: aggregator-service-envs
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 150Mi