apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentcreator
spec:
  selector:
    matchLabels:
      app: contentcreator
  template:
    metadata:
      labels:
        app: contentcreator
    spec:
      containers:
        - name: contentcreator
          image: gcr.io/dynatrace-demoability/easytrade/contentcreator:151f288
          env:
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: JAVA_CONNECTION_STRING
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 300Mi
