apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    owner: team-platform
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        owner: team-platform
    spec:
      containers:
        - name: db
          image: gcr.io/dynatrace-demoability/easytrade/db:151f288
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "yourStrong(!)Password"
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 1.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
